# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_1_rindang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCzRb9xz5yES6KpTqXf_bzHq4SkFp7wD
"""

#1. Sebutkan pengalaman kamu dalam bahasa pemograman python
#   Pengalaman saya sebelumnya mengikuti kelas python data science basic yang diselenggarakan oleh sanbercode, kelas tersebut sangat menyenangkan, 
#   dan menambah wawasan saya, meskipun masih ada beberapa hal yang belum saya kuasai, oleh kerana itu saya tertarik untuk bergabung di kelas lanjutan ini    
#2. Kelas python lanjutan apa saja yang kamu harapkan ada di sanbercode kedepannya?
#   Mungkin bisa ditambahkan kelas lanjutan dengan lebih banyak studi kasus terutama yang berkaitan dengan real case

#3
class manipulasi:
  def __init__(self, data):
    self.data = data

  def function(self):
    print('data = ' + self.data)
    print(self.data.upper())
    print(self.data.capitalize())
    print(self.data.lower())
    print(self.data.split())
data1 = manipulasi('saya tinggal di Indonesia')
data1.function()