# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_1_rindang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCzRb9xz5yES6KpTqXf_bzHq4SkFp7wD
"""

class manipulasi:
  def __init__(self, data):
    self.data = data

  def function(self):
    print('data = ' + self.data)
    print(self.data.upper())
    print(self.data.capitalize())
    print(self.data.lower())
    print(self.data.split())
data1 = manipulasi('saya tinggal di Indonesia')
data1.function()
