# -*- coding: utf-8 -*-
"""Tugaspythonlanjutan_hari2_rindang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rLKuKsBR6SaGqyXE5WK9oVWDvOP8XY2m
"""

import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, Series, Reference
import csv

def create_excel():
  #preprocessing
  df1 = pd.read_csv('jumlah-penduduk-kota-bandung.csv') #read data csv 1
  df1.sort_values(by='Kecamatan  ')
  df2 = pd.read_csv('luas-wilayah-menurut-kecamatan-di-kota-bandung-2017.csv') #read data csv 2
  df3 = df1.merge(df2, left_on= 'Kecamatan  ', right_on= 'Nama Kecamatan', how = 'left') #merge csv 1 dan csv 2
  df3[df3['Nama Kecamatan'].isna()] #ada nilai NaN
  df2 = pd.read_csv('luas-wilayah-menurut-kecamatan-di-kota-bandung-2017.csv') #read data csv 2 dan menyamakan nama kecamatan
  df2['Nama Kecamatan'] = df2['Nama Kecamatan'].replace(['Astana Anyar', 'Ujungberung', 'Buahbatu'],['Astanaanyar', 'Ujung Berung', 'Buah Batu'])
  df3 = df1.merge(df2, left_on= 'Kecamatan  ', right_on= 'Nama Kecamatan') #merge csv 1 dan csv 2
  df3 = df3.drop(columns=['Nama Kecamatan']) #drop kolom Nama Kecamatan
  population_density_100 = (df3['Jumlah_Penduduk']/df3['Luas Wilayah (m2)'])*100 #calculate density
  population_density_100
  pop = population_density_100
  pop.head()
  df3['Kepadatan Penduduk'] = pop
  df3 = df3.sort_values(by='Kecamatan  ')
  df3 = df3.drop(columns=['Jumlah_Kelurahan', 'Jumlah_Penduduk','Luas Wilayah (m2)']) #drop kolom yang tidak perlu
  df3.to_csv('data.csv', index = False) #save to csv

  wb = Workbook(write_only=True)
  ws = wb.create_sheet()

  #open file
  data = open('data.csv')
  rows = csv.reader(data, delimiter= ',')
  
  index = 0
  for row in rows:
    data_clean = []
    for i in row :
      try:
        
          i = float(i)
      except:
          pass
      data_clean.append(i)
    ws.append(data_clean)
    index += 1
  
  chart1 = BarChart()
  chart1.type= 'col'
  chart1.style =3
  chart1.title = 'Kepadatan Penduduk'
  chart1.x_axis.title = 'Kecamatan'
  chart1.y_axis.title = 'Kepadatan Penduduk'
  
  data = Reference(ws, min_col=2, min_row=1, max_row=index, max_col=2)
  cats = Reference(ws, min_col=1, min_row=2, max_row=index)
  chart1.height = 10# default is 7.5
  chart1.width = 30 # default is 15
  chart1.add_data(data, titles_from_data=True)
  chart1.set_categories(cats)
  ws.add_chart(chart1, "G2")

  wb.save("rindang.xlsx")


create_excel()